create table cancel_order(
  payment_method CHAR(40),
  restaurant_id int,
  customer_phone_number char(20),
  payment_confirmation_channel char(30),
  order_spending FLOAT ,
  cart_id bigint,
  distance_calc_method char(30),
  free_shipping tinyint,
  actual_sla_time FLOAT ,
  uuid CHARACTER VARYING(100),
  customer_user_agent CHARACTER VARYING (300),
  event_id bigint,
  pg_response_time TIMESTAMP ,
  customer_delivery_address CHARACTER VARYING (1000),
  order_incoming FLOAT ,
  payment_txn_status CHAR (30),
  delivery_address_geo_hash CHAR (20),
  coupon_applied tinyint,
  sid CHARACTER VARYING (100),
  time_stamp bigint,
  app_version CHAR (30),
  with_de tinyint,
  coupon_discount float,
  reverse_geo_code_failed tinyint,
  is_assured tinyint,
  order_tax FLOAT ,
  payment_netbanking_type CHARACTER VARYING (100),
  convenience_fee float,
  sla_time float,
order_delivery_charge FLOAT ,
order_discount FLOAT ,
delivery_lat_lng CHARACTER varying(100),
is_select tinyint,
order_status CHARACTER varying(40),
order_total float,
swiggy_money FLOAT ,
order_time TIMESTAMP ,
swuid CHARACTER varying(100),
device_id CHARACTER varying(100),
cust_lat_lng CHARACTER varying(100),
customer_id CHARACTER varying(100),
order_delivery_status CHARACTER varying(40),
converted_to_cod tinyint,
cancellation_fee_applied tinyint,
error_message CHARACTER VARYING (100),
sla_difference tinyint,
delayed_placing tinyint,
user_agent CHARACTER VARYING (300),
cust_geo_hash CHARACTER (20),
original_order_total FLOAT ,
is_replicated tinyint,
last_failed_order_id INTEGER
);