CREATE TABLE place_order(
  sid VARCHAR(100),
  tid VARCHAR(100),
  swuid VARCHAR(100),
  user_agent VARCHAR(30),
  ip_address VARCHAR(30),
  device_id VARCHAR(100),
  customer_id BIGINT,
  request_id VARCHAR(100),
  app_version VARCHAR(20),
  success BOOLEAN,
  error_message VARCHAR(100),
  banner_factor FLOAT,
  start_banner_factor FLOAT,
  stop_banner_factor FLOAT,
  mobile VARCHAR(20),
  payment_netbanking_type VARCHAR(100),
  card_bin_number VARCHAR(100),
  cart_id BIGINT,

  order_id BIGINT,
  ordered_time_in_seconds BIGINT,
  restaurant_id BIGINT,
  order_total FLOAT,
  order_restaurant_bill FLOAT,
  restaurant_customer_distance FLOAT,
  is_refund_initiated BOOLEAN,

  sla_time FLOAT,
  swiggy_money FLOAT,
  convenience_fee FLOAT,
  is_assured tinyint,
  coupon_applied VARCHAR(20),
  order_status VARCHAR(40),
  order_delivery_status VARCHAR(40),
  original_order_total FLOAT,
  order_tax FLOAT,
  free_shipping tinyint,
  order_discount FLOAT,
  coupon_discount FLOAT,
  order_spending FLOAT,
  order_incoming FLOAT,
  last_failed_order_id BIGINT,
  order_delivery_charge FLOAT,
  customer_user_agent VARCHAR(40),
  payment_confirmation_channel VARCHAR(40),
  distance_calc_method VARCHAR(40),
  customer_ip VARCHAR(40),
  sla_difference FLOAT,
  actual_sla_time FLOAT,
  payment_txn_status VARCHAR(40),
  cancellation_fee_applied FLOAT,
  payment_method VARCHAR(40),

  converted_to_cod BOOLEAN,
  cust_lat_lng VARCHAR(100),
  cust_geo_hash VARCHAR(40),
  with_de BOOLEAN,
  is_replicated BOOLEAN,
  is_select BOOLEAN,
  delivery_address TEXT,

  reverse_geo_code_faile BOOLEAN,

  delivery_lat_lng VARCHAR(100),
  delivery_geo_hash VARCHAR(40),

  order_time BIGINT,
  pg_response_time BIGINT
);